import 'package:opendray/core/i18n/strings.g.dart';

/// Source strings also live in app/i18n/{en,es,zh}.json. This adapter keeps
/// the feature compilable in source-only environments where slang codegen is
/// deliberately deferred to the final Flutter runtime gate.
class AgentTasksStrings {
  factory AgentTasksStrings() =>
      AgentTasksStrings._(switch (LocaleSettings.currentLocale) {
        AppLocale.es => _spanish,
        AppLocale.zh => _chinese,
        AppLocale.en => _english,
      });

  const AgentTasksStrings._(this._values);

  final Map<String, String> _values;

  String call(String key) => _values[key] ?? _english[key] ?? key;

  static final AgentTasksStrings current = AgentTasksStrings();
}

const _english = <String, String>{
  'navLabel': 'Tasks',
  'title': 'Agent Tasks',
  'create': 'New task',
  'emptyTitle': 'No agent tasks',
  'emptyBody':
      'Create a non-interactive agent task. Terminal sessions remain separate.',
  'refresh': 'Refresh',
  'all': 'All',
  'allProjects': 'All projects',
  'loadMore': 'Load more',
  'offline': 'Offline. Showing the last loaded state.',
  'retry': 'Retry',
  'project': 'Project',
  'provider': 'Provider',
  'prompt': 'Prompt',
  'workspace': 'Workspace',
  'contextMode': 'Context',
  'newContext': 'New context',
  'continueContext': 'Continue context',
  'attachments': 'Attachments',
  'pickAttachments': 'Choose files',
  'timeout': 'Timeout (seconds)',
  'telegramNotify': 'Notify in Telegram',
  'submit': 'Create task',
  'creating': 'Creating…',
  'required': 'This field is required',
  'invalidTimeout': 'Enter a timeout between 30 and 86400 seconds',
  'details': 'Task details',
  'runs': 'Runs',
  'events': 'Output',
  'artifacts': 'Artifacts',
  'continueAction': 'Continue',
  'cancelAction': 'Cancel',
  'confirm': 'Confirm',
  'retryAction': 'Retry',
  'confirmCancel': 'Cancel this task and terminate its active process tree?',
  'confirmRetry': 'Create a new retry run?',
  'waitingInput': 'Input required',
  'continueHint': 'Enter follow-up instructions',
  'send': 'Send',
  'stdout': 'stdout',
  'stderr': 'stderr',
  'raw': 'raw',
  'download': 'Download',
  'verified': 'Integrity verified',
  'downloadFailed': 'Artifact download failed',
  'noRuns': 'No runs yet',
  'noOutput': 'No output yet',
  'source': 'Source',
  'status': 'Status',
  'created': 'Created',
  'updated': 'Updated',
  'context': 'Runtime context',
  'currentRun': 'Current run',
  'networkError': 'Network request failed',
  'permissionError': 'You do not have permission for this operation',
  'sessionIsolation':
      'One-shot tasks do not open or write to terminal sessions.',
  'capabilityResume': 'Resume',
  'capabilityAttachment': 'Attachments',
  'smallScreenHint': 'Fields are stacked for small screens.',
  'filterStatus': 'Status filter',
  'taskCreated': 'Task created',
  'actionFailed': 'Action failed',
  'loading': 'Loading…',
  'open': 'Open',
  'timeline': 'Timeline',
  'result': 'Result',
  'idempotent': 'Duplicate taps reuse the same idempotency key.',
  'telegramSource': 'Telegram',
  'mobileSource': 'Mobile',
  'apiSource': 'API',
  'unknownSource': 'Unknown',
  'cancelled': 'Cancelled',
  'completed': 'Completed',
  'failed': 'Failed',
  'timedOut': 'Timed out',
  'running': 'Running',
  'queued': 'Queued',
  'pending': 'Pending',
  'waiting': 'Waiting for input',
  'unknown': 'Unknown',
};

final _spanish = <String, String>{
  ..._english,
  'navLabel': 'Tareas',
  'title': 'Tareas de agente',
  'create': 'Nueva tarea',
  'emptyTitle': 'No hay tareas de agente',
  'emptyBody':
      'Crea una tarea de agente no interactiva. Las sesiones de terminal permanecen separadas.',
  'refresh': 'Actualizar',
  'all': 'Todas',
  'allProjects': 'Todos los proyectos',
  'loadMore': 'Cargar más',
  'offline': 'Sin conexión. Se muestra el último estado cargado.',
  'project': 'Proyecto',
  'provider': 'Proveedor',
  'prompt': 'Instrucción',
  'workspace': 'Espacio de trabajo',
  'newContext': 'Contexto nuevo',
  'continueContext': 'Continuar contexto',
  'attachments': 'Adjuntos',
  'pickAttachments': 'Elegir archivos',
  'telegramNotify': 'Notificar en Telegram',
  'submit': 'Crear tarea',
  'creating': 'Creando…',
  'required': 'Este campo es obligatorio',
  'details': 'Detalles de la tarea',
  'runs': 'Ejecuciones',
  'events': 'Salida',
  'artifacts': 'Artefactos',
  'continueAction': 'Continuar',
  'cancelAction': 'Cancelar',
  'confirm': 'Confirmar',
  'waitingInput': 'Se requiere entrada',
  'continueHint': 'Introduce instrucciones de seguimiento',
  'send': 'Enviar',
  'download': 'Descargar',
  'verified': 'Integridad verificada',
  'noRuns': 'Aún no hay ejecuciones',
  'noOutput': 'Aún no hay salida',
  'source': 'Origen',
  'status': 'Estado',
  'created': 'Creada',
  'updated': 'Actualizada',
  'networkError': 'Falló la solicitud de red',
  'permissionError': 'No tienes permiso para esta operación',
  'cancelled': 'Cancelada',
  'completed': 'Completada',
  'failed': 'Fallida',
  'timedOut': 'Tiempo agotado',
  'running': 'En ejecución',
  'queued': 'En cola',
  'pending': 'Pendiente',
  'waiting': 'Esperando entrada',
  'unknown': 'Desconocido',
};

final _chinese = <String, String>{
  ..._english,
  'navLabel': '任务',
  'title': 'Agent 任务',
  'create': '新建任务',
  'emptyTitle': '暂无 Agent 任务',
  'emptyBody': '创建非交互式 Agent 任务。终端会话保持独立。',
  'refresh': '刷新',
  'all': '全部',
  'allProjects': '全部项目',
  'loadMore': '加载更多',
  'offline': '网络已断开，正在显示最近一次加载的状态。',
  'retry': '重试',
  'project': '项目',
  'provider': 'Provider',
  'prompt': '任务指令',
  'workspace': '工作目录',
  'contextMode': '上下文',
  'newContext': '新上下文',
  'continueContext': '继续上下文',
  'attachments': '附件',
  'pickAttachments': '选择文件',
  'timeout': '超时秒数',
  'telegramNotify': '完成后通知 Telegram',
  'submit': '创建任务',
  'creating': '正在创建…',
  'required': '此项必填',
  'invalidTimeout': '请输入 30 到 86400 秒之间的超时时间',
  'details': '任务详情',
  'runs': '运行记录',
  'events': '实时输出',
  'artifacts': '制品',
  'continueAction': '继续',
  'cancelAction': '取消',
  'confirm': '确认',
  'retryAction': '重试',
  'confirmCancel': '确认取消该任务并终止当前进程树？',
  'confirmRetry': '确认创建新的重试 Run？',
  'waitingInput': '等待补充输入',
  'continueHint': '输入后续指令',
  'send': '发送',
  'stdout': '标准输出',
  'stderr': '标准错误',
  'raw': '原始事件',
  'download': '下载',
  'verified': '完整性校验通过',
  'downloadFailed': '制品下载失败',
  'noRuns': '暂无 Run',
  'noOutput': '暂无输出',
  'source': '来源',
  'status': '状态',
  'created': '创建时间',
  'updated': '更新时间',
  'context': '运行上下文',
  'currentRun': '当前 Run',
  'networkError': '网络请求失败',
  'permissionError': '当前账号没有此操作权限',
  'sessionIsolation': 'One-shot 任务不会打开或写入终端会话。',
  'capabilityResume': '支持继续',
  'capabilityAttachment': '支持附件',
  'smallScreenHint': '小屏设备会自动纵向排列字段。',
  'filterStatus': '状态筛选',
  'taskCreated': '任务已创建',
  'actionFailed': '操作失败',
  'loading': '加载中…',
  'open': '打开',
  'timeline': '时间线',
  'result': '结果',
  'idempotent': '重复点击会复用同一个幂等键。',
  'telegramSource': 'Telegram',
  'mobileSource': '移动端',
  'apiSource': 'API',
  'unknownSource': '未知',
  'cancelled': '已取消',
  'completed': '已完成',
  'failed': '失败',
  'timedOut': '已超时',
  'running': '运行中',
  'queued': '排队中',
  'pending': '待处理',
  'waiting': '等待输入',
  'unknown': '未知',
};
