-- 0027_project_docs_tech_stack — widen project_docs.kind to allow
-- 'tech_stack', a new system-managed doc generated by the project
-- scanner (internal/projectscan). M16 / Phase B of the long-term
-- memory hygiene pipeline.
--
-- Why a new kind rather than a separate table: tech_stack is the
-- same "one markdown body per cwd, replace-in-place" shape as
-- goal / plan, just managed by the scanner instead of an operator.
-- Reusing the project_docs schema means it gets the file mirror,
-- spawn-time injection, and proposal flow for free.
--
-- The new value 'tech_stack' is unique to this kind:
--   - updated_by = 'scanner' (new CHECK relaxation below) — never
--     hand-edited by an operator; the scanner overwrites it on
--     each scan pass.
--   - No proposal flow: scanner writes directly via PutDoc with
--     updated_by='scanner'. Operators cannot "approve" a tech
--     stack the way they approve a goal/plan change — the scan
--     output is mechanical, not a judgment call.

ALTER TABLE project_docs DROP CONSTRAINT IF EXISTS project_docs_kind_check;
ALTER TABLE project_docs ADD CONSTRAINT project_docs_kind_check
    CHECK (kind IN ('goal', 'plan', 'tech_stack'));

ALTER TABLE project_docs DROP CONSTRAINT IF EXISTS project_docs_updated_by_check;
ALTER TABLE project_docs ADD CONSTRAINT project_docs_updated_by_check
    CHECK (updated_by IN ('operator', 'agent', 'scanner'));
