package projectdoc

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Mirror writes the project's goal, plan and recent journal entries
// to `<cwd>/.opendray/{GOAL,PLAN,JOURNAL}.md` as a plain-text fallback
// for operators who prefer reading them with a normal editor (or for
// agents that can't reach the gateway API and want to grep the
// markdown directly).
//
// Direction: DB → file. M10 ships with the one-way path; the
// reverse direction (file → DB → proposal) is a future enhancement.
//
// The .opendray/ dir is gitignored via a .gitignore file dropped on
// first write — these mirrors are per-clone state and should not
// accumulate in version control.
//
// All filesystem errors are non-fatal: returned as the function
// result so callers can log them, but the DB write that triggered
// the mirror is never rolled back. Operators who run opendray as a
// different user than the cwd owner just won't get mirrors — the
// DB stays consistent.
func (s *Service) Mirror(ctx context.Context, cwd string) error {
	if strings.TrimSpace(cwd) == "" {
		return ErrEmptyCwd
	}
	info, err := os.Stat(cwd)
	if err != nil {
		return fmt.Errorf("projectdoc: mirror stat cwd: %w", err)
	}
	if !info.IsDir() {
		return fmt.Errorf("projectdoc: mirror cwd is not a directory: %s", cwd)
	}

	dir := filepath.Join(cwd, ".opendray")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("projectdoc: mirror mkdir: %w", err)
	}

	// Drop a .gitignore on first creation. Idempotent — we always
	// write it; if it already exists with the same content there's
	// no diff. Hand-crafted note included so a curious operator who
	// runs `cat .opendray/.gitignore` understands why it's here.
	gitignore := "# Generated by opendray. Mirrors of project_docs / session_logs.\n" +
		"# DB is the source of truth; these files are read-only convenience.\n" +
		"*\n"
	if err := writeIfDifferent(filepath.Join(dir, ".gitignore"), gitignore); err != nil {
		return fmt.Errorf("projectdoc: mirror .gitignore: %w", err)
	}

	docs, err := s.ListDocsForCwd(ctx, cwd)
	if err != nil {
		return fmt.Errorf("projectdoc: mirror list docs: %w", err)
	}
	logs, err := s.ListLogs(ctx, cwd, 50)
	if err != nil {
		return fmt.Errorf("projectdoc: mirror list logs: %w", err)
	}

	// Cortex Phase 3 — every blueprint section mirrors to its own
	// `<SLUG>.md` (GOAL.md / PLAN.md keep their historical names for
	// free since the slugs match). Sections currently in the blueprint
	// always get a file (empty content = empty file) so deleting the
	// content empties the mirror instead of leaving a stale copy.
	sections, sErr := s.ListSections(ctx, cwd)
	if sErr != nil {
		// Blueprint unavailable (e.g. un-migrated test DB): fall back
		// to the default set so GOAL/PLAN keep mirroring.
		sections = defaultSections(cwd)
	}
	content := make(map[string]string, len(docs))
	for _, d := range docs {
		content[string(d.Kind)] = d.Content
	}
	for _, sec := range sections {
		name := strings.ToUpper(sec.Slug) + ".md"
		if err := writeIfDifferent(filepath.Join(dir, name), content[sec.Slug]); err != nil {
			return fmt.Errorf("projectdoc: mirror %s: %w", name, err)
		}
	}
	if err := writeIfDifferent(filepath.Join(dir, "JOURNAL.md"), renderJournalFile(logs)); err != nil {
		return fmt.Errorf("projectdoc: mirror JOURNAL.md: %w", err)
	}
	return nil
}

// renderJournalFile formats session_logs as a single markdown file.
// Newest-first; each entry rendered with title + timestamp + author +
// content. Kept deterministic so re-running Mirror over the same
// state produces byte-identical output (avoids spurious "modified"
// indicators in the operator's editor).
func renderJournalFile(logs []LogEntry) string {
	if len(logs) == 0 {
		return "# Project journal\n\n_No entries yet._\n"
	}
	var b strings.Builder
	b.WriteString("# Project journal\n\n")
	for _, e := range logs {
		title := e.Title
		if title == "" {
			title = "(untitled)"
		}
		fmt.Fprintf(&b, "## %s\n\n", title)
		fmt.Fprintf(&b, "_%s · %s · %s_\n\n",
			e.Kind, e.UpdatedBy, e.CreatedAt.UTC().Format(time.RFC3339))
		body := strings.TrimSpace(e.Content)
		if body == "" {
			b.WriteString("_(empty)_\n")
		} else {
			b.WriteString(body)
			b.WriteString("\n")
		}
		b.WriteString("\n---\n\n")
	}
	return b.String()
}

// writeIfDifferent only touches disk when the content actually
// changes. Saves operators watching their git status / IDE diff
// indicators from noise after every memory write.
func writeIfDifferent(path, content string) error {
	cur, err := os.ReadFile(path)
	if err == nil && string(cur) == content {
		return nil
	}
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	// Atomic: write a temp file in the same dir, then rename. Lets
	// readers (e.g. the agent's grep) never see a partial write.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
