#!/usr/bin/env bash
# enable-cli-updates.sh — give the opendray service its own writable npm
# prefix so the dashboard's in-app "Update" button on each provider
# (Claude / Gemini / Codex) actually works on a non-root install.
#
# Why: `npm install -g <pkg>` writes under whatever `npm root -g` resolves
# to. On most installs that's a root-owned dir (/usr/lib/node_modules or
# /opt/homebrew/...), which the opendray service user can't write — so
# the catalog upgrade endpoint correctly returns "unavailable, prefix
# read-only". This one-shot script flips that by:
#   1. Creating ~/.npm-global under the service user's HOME.
#   2. Writing a systemd drop-in that sets NPM_CONFIG_PREFIX + prepends
#      $HOME/.npm-global/bin onto PATH for the opendray unit.
#   3. Installing claude / gemini / codex into that prefix as the service
#      user, so they're the ones opendray picks up on its next start.
#   4. Reloading systemd + restarting opendray.
#
# Idempotent — safe to re-run; it'll just re-install latest into the
# prefix. Skip a CLI with SKIP_CLAUDE=1 / SKIP_GEMINI=1 / SKIP_CODEX=1.
#
# Run as root on the opendray host:
#   sudo bash scripts/enable-cli-updates.sh

set -euo pipefail

: "${OPENDRAY_DATA_DIR:=/var/lib/opendray}"
: "${OPENDRAY_SERVICE_USER:=opendray}"
: "${OPENDRAY_SERVICE_NAME:=opendray}"
: "${SKIP_CLAUDE:=0}"
: "${SKIP_GEMINI:=0}"
: "${SKIP_CODEX:=0}"

NPM_PREFIX="$OPENDRAY_DATA_DIR/.npm-global"
DROPIN_DIR="/etc/systemd/system/${OPENDRAY_SERVICE_NAME}.service.d"
DROPIN_FILE="$DROPIN_DIR/npm-prefix.conf"

CLAUDE_PKG="@anthropic-ai/claude-code"
GEMINI_PKG="@google/gemini-cli"
CODEX_PKG="@openai/codex"

[[ $EUID -eq 0 ]] || { echo "must run as root"; exit 1; }
id "$OPENDRAY_SERVICE_USER" >/dev/null 2>&1 \
    || { echo "service user '$OPENDRAY_SERVICE_USER' does not exist"; exit 1; }
command -v npm >/dev/null \
    || { echo "npm not found on PATH"; exit 1; }

echo "[1/5] create writable npm prefix: $NPM_PREFIX"
install -d -m 0755 -o "$OPENDRAY_SERVICE_USER" -g "$OPENDRAY_SERVICE_USER" "$NPM_PREFIX"
install -d -m 0755 -o "$OPENDRAY_SERVICE_USER" -g "$OPENDRAY_SERVICE_USER" "$NPM_PREFIX/bin"
install -d -m 0755 -o "$OPENDRAY_SERVICE_USER" -g "$OPENDRAY_SERVICE_USER" "$NPM_PREFIX/lib"

echo "[2/5] pin npm prefix for service user (~/.npmrc)"
sudo -u "$OPENDRAY_SERVICE_USER" -H npm config set prefix "$NPM_PREFIX"

echo "[3/5] install / refresh CLIs into the prefix (as $OPENDRAY_SERVICE_USER)"
install_pkg() {
    local pkg="$1"
    echo "    → npm install -g $pkg"
    if ! sudo -u "$OPENDRAY_SERVICE_USER" -H \
            env PATH="$NPM_PREFIX/bin:$PATH" NPM_CONFIG_PREFIX="$NPM_PREFIX" \
            npm install -g "$pkg" 2>&1 | tail -3; then
        echo "      ⚠ $pkg failed — skipping; the dashboard's Update button will"
        echo "        stay 'unavailable' for this provider until it installs."
    fi
}
[[ "$SKIP_CLAUDE" = 1 ]] || install_pkg "$CLAUDE_PKG"
[[ "$SKIP_GEMINI" = 1 ]] || install_pkg "$GEMINI_PKG"
[[ "$SKIP_CODEX"  = 1 ]] || install_pkg "$CODEX_PKG"

echo "[4/5] write systemd drop-in: $DROPIN_FILE"
install -d -m 0755 "$DROPIN_DIR"
# The drop-in is additive — it only sets NPM_CONFIG_PREFIX and prepends
# the prefix's bin onto PATH. The base unit's other env (set via
# EnvironmentFile=) is preserved.
cat >"$DROPIN_FILE" <<EOF
# Generated by scripts/enable-cli-updates.sh. Gives the opendray service
# a writable npm prefix so in-app CLI upgrades work on non-root installs.
[Service]
Environment="NPM_CONFIG_PREFIX=$NPM_PREFIX"
Environment="PATH=$NPM_PREFIX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
EOF
chmod 0644 "$DROPIN_FILE"

echo "[5/5] reload systemd + restart $OPENDRAY_SERVICE_NAME"
systemctl daemon-reload
systemctl restart "$OPENDRAY_SERVICE_NAME"
sleep 2
if systemctl is-active --quiet "$OPENDRAY_SERVICE_NAME"; then
    echo "      ✓ $OPENDRAY_SERVICE_NAME is running"
else
    echo "      ⚠ $OPENDRAY_SERVICE_NAME failed to start — see: journalctl -u $OPENDRAY_SERVICE_NAME -n 50"
    exit 1
fi

echo
echo "Done. In Providers → each CLI tab the 'Update' button now writes into"
echo "$NPM_PREFIX, so one-tap upgrades work."
echo
echo "Installed in the prefix:"
ls -la "$NPM_PREFIX/bin" 2>/dev/null | sed 's/^/  /' || true
